"""add venue_id to cohorts

Revision ID: 9b024fb7a910
Revises: cbf1c50a050e
Create Date: 2026-08-03 15:08:53.885496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b024fb7a910'
down_revision: Union[str, Sequence[str], None] = 'cbf1c50a050e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cohorts', sa.Column('venue_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'cohorts', 'venues', ['venue_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cohorts', type_='foreignkey')
    op.drop_column('cohorts', 'venue_id')
    # ### end Alembic commands ###
