"""add city and capacity to venues

Revision ID: cbf1c50a050e
Revises: ae4c8b2e7629
Create Date: 2026-08-03 14:11:14.567769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbf1c50a050e'
down_revision: Union[str, Sequence[str], None] = 'ae4c8b2e7629'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('city', sa.String(length=100), nullable=False))
    op.add_column('venues', sa.Column('capacity', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'capacity')
    op.drop_column('venues', 'city')
    # ### end Alembic commands ###
